import type { Element, ElementContent, Root } from 'hast';

const NOT_CODE = new Set(['language-math', 'math-display', 'math-inline']);

function classesOf(node: Element): string[] {
  const classes = node.properties?.className;
  return Array.isArray(classes) ? classes.map(String) : [String(classes ?? '')];
}

function languageOf(code: Element): string | undefined {
  const match = classesOf(code).find((name) => name.startsWith('language-'));
  return match?.slice('language-'.length);
}

/**
 * Splits highlighted code into one array of nodes per line. A token can span a
 * newline — a block comment, a template string — so an element that does is
 * cloned into each line it covers rather than closed at the first break.
 */
function splitLines(nodes: ElementContent[]): ElementContent[][] {
  const lines: ElementContent[][] = [[]];
  const add = (node: ElementContent) => lines[lines.length - 1].push(node);

  for (const node of nodes) {
    if (node.type === 'text') {
      node.value.split('\n').forEach((part, index) => {
        if (index > 0) lines.push([]);
        if (part) add({ type: 'text', value: part });
      });
      continue;
    }

    if (node.type === 'element') {
      splitLines(node.children).forEach((children, index) => {
        if (index > 0) lines.push([]);
        if (children.length > 0) add({ ...node, children });
      });
      continue;
    }

    add(node);
  }

  return lines;
}

/**
 * Wraps each line in a span the stylesheet can number. The newline stays inside
 * the span, so the block still breaks where it did and `textContent` — what the
 * copy button reads — is the source, unchanged. The numbers themselves are
 * generated by a CSS counter, which keeps them out of the clipboard.
 */
function numberLines(code: Element): boolean {
  const lines = splitLines(code.children);
  // A file ending in a newline produces a last, empty line.
  if (lines.length > 1 && lines[lines.length - 1].length === 0) lines.pop();
  if (lines.length < 2) return false;

  code.children = lines.map((children, index) => ({
    type: 'element',
    tagName: 'span',
    properties: { className: ['code-line'] },
    children: index === lines.length - 1 ? children : [...children, { type: 'text', value: '\n' }],
  }));

  return true;
}

/**
 * Wraps every `pre` in the chrome the reader sees — a bar carrying the language
 * and a copy button, above the code rather than over it — at build time, so a
 * prerendered page has them before any script runs. The button only needs a
 * click handler attached later.
 */
export function rehypeCodeBlocks() {
  return (tree: Root) => {
    const walk = (node: Root | Element) => {
      const children = 'children' in node ? node.children : [];
      children.forEach((child, index) => {
        if (child.type !== 'element') return;
        if (child.tagName !== 'pre') {
          walk(child);
          return;
        }

        const code = child.children.find(
          (grandchild): grandchild is Element =>
            grandchild.type === 'element' && grandchild.tagName === 'code',
        );
        if (code && classesOf(code).some((name) => NOT_CODE.has(name))) return;
        const language = code ? languageOf(code) : undefined;

        // The number gutter supplies the padding on a numbered block, so that
        // it can stay put while a long line scrolls under it.
        const numbered = code ? numberLines(code) : false;

        // A block that scrolls sideways has to be reachable by keyboard.
        child.properties = {
          ...child.properties,
          tabIndex: 0,
          ...(numbered ? { className: ['numbered'] } : {}),
        };

        const bar: Element[] = [];
        if (language) {
          bar.push({
            type: 'element',
            tagName: 'span',
            properties: { className: ['code-block__lang'], ariaHidden: 'true' },
            children: [{ type: 'text', value: language }],
          });
        }
        bar.push({
          type: 'element',
          tagName: 'button',
          properties: { type: 'button', className: ['code-block__copy'] },
          children: [
            { type: 'text', value: 'copy' },
            {
              type: 'element',
              tagName: 'span',
              properties: { className: ['visually-hidden'] },
              children: [{ type: 'text', value: ' code to clipboard' }],
            },
          ],
        });

        children[index] = {
          type: 'element',
          tagName: 'div',
          properties: { className: ['code-block'] },
          children: [
            {
              type: 'element',
              tagName: 'div',
              properties: { className: ['code-block__bar'] },
              children: bar,
            },
            child,
          ],
        };
      });
    };
    walk(tree);
  };
}
